# Generated by Django 6.0.3 on 2026-03-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DATA_API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="data",
            name="launch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telemetries",
                to="DATA_API.launch",
            ),
            preserve_default=False,
        ),
    ]
