# Generated by Django 5.1.15 on 2026-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DATA_API", "0002_launch_data_launch"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="is_recording",
            field=models.BooleanField(default=True),
        ),
    ]
